export const routes = {
  login: '/login',
  signup: '/signup',
  home: '/',
  paises: '/paises',
  departamentos: '/departamentos',
  ciudades: '/ciudades',
  zonas: '/zonas',
  diocesis: '/diocesis',
  parroquias: '/parroquias',
  parroquia: (id: string | number) => `/parroquias/detalle?id=${id}`,
  etapas: '/etapas',
  tiposEquipo: '/tipos-equipo',
  personas: '/personas',
  comunidades: '/comunidades',
  comunidad: (id: string | number) => `/comunidades/detalle?id=${id}`,
  equipoNacional: '/equipo-nacional',
  reportes: '/reportes',
  reporteCatequistas: '/reportes/equipos-catequistas',
  reportePresbiteros: '/reportes/presbiteros',
  reporteEstadoPasos: '/reportes/estado-pasos',
  reporteLideres: '/reportes/lideres-comunidades',
  reporteCatequesisParroquia: '/reportes/catequesis-parroquia',
  cuenta: '/cuenta',
  admin: '/admin',
  publico: '/publico',
  authConfirm: '/auth/confirm',
} as const;

export const publicRoutes = [
  routes.login, routes.signup, routes.publico,
  routes.authConfirm,
];
