-- Migration: Add dioceses table and replace parishes.diocese text field with FK
-- This migration creates a master dioceses table for all Colombian ecclesiastical jurisdictions,
-- migrates existing text data, and updates report views.

BEGIN;

-- ==============================================
-- 1. Create dioceses table
-- ==============================================
CREATE TABLE public.dioceses (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(256) NOT NULL UNIQUE,
    type varchar(50) NOT NULL,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

-- Add check constraint for valid types
ALTER TABLE public.dioceses
    ADD CONSTRAINT dioceses_type_check
    CHECK (type IN ('arquidiocesis', 'diocesis', 'vicariato_apostolico', 'ordinariato_militar', 'exarcado_apostolico'));

-- ==============================================
-- 2. Insert all Colombian ecclesiastical jurisdictions
-- ==============================================

-- Arquidiócesis (14)
INSERT INTO public.dioceses (name, type) VALUES
    ('Arquidiócesis de Bogotá', 'arquidiocesis'),
    ('Arquidiócesis de Barranquilla', 'arquidiocesis'),
    ('Arquidiócesis de Bucaramanga', 'arquidiocesis'),
    ('Arquidiócesis de Cali', 'arquidiocesis'),
    ('Arquidiócesis de Cartagena de Indias', 'arquidiocesis'),
    ('Arquidiócesis de Ibagué', 'arquidiocesis'),
    ('Arquidiócesis de Manizales', 'arquidiocesis'),
    ('Arquidiócesis de Medellín', 'arquidiocesis'),
    ('Arquidiócesis de Nueva Pamplona', 'arquidiocesis'),
    ('Arquidiócesis de Popayán', 'arquidiocesis'),
    ('Arquidiócesis de Santa Fe de Antioquia', 'arquidiocesis'),
    ('Arquidiócesis de Tunja', 'arquidiocesis'),
    ('Arquidiócesis de Villavicencio', 'arquidiocesis'),
    ('Arquidiócesis de Pasto', 'arquidiocesis');

-- Diócesis (52)
INSERT INTO public.dioceses (name, type) VALUES
    ('Diócesis de Apartadó', 'diocesis'),
    ('Diócesis de Armenia', 'diocesis'),
    ('Diócesis de Barrancabermeja', 'diocesis'),
    ('Diócesis de Buga', 'diocesis'),
    ('Diócesis de Caldas', 'diocesis'),
    ('Diócesis de Cartago', 'diocesis'),
    ('Diócesis de Chiquinquirá', 'diocesis'),
    ('Diócesis de Cúcuta', 'diocesis'),
    ('Diócesis de Duitama-Sogamoso', 'diocesis'),
    ('Diócesis de El Espinal', 'diocesis'),
    ('Diócesis de Engativá', 'diocesis'),
    ('Diócesis de Facatativá', 'diocesis'),
    ('Diócesis de Florencia', 'diocesis'),
    ('Diócesis de Fontibón', 'diocesis'),
    ('Diócesis de Garzón', 'diocesis'),
    ('Diócesis de Girardot', 'diocesis'),
    ('Diócesis de Granada en Colombia', 'diocesis'),
    ('Diócesis de Ipiales', 'diocesis'),
    ('Diócesis de Istmina-Tadó', 'diocesis'),
    ('Diócesis de Jericó', 'diocesis'),
    ('Diócesis de La Dorada-Guaduas', 'diocesis'),
    ('Diócesis de Líbano-Honda', 'diocesis'),
    ('Diócesis de Magangué', 'diocesis'),
    ('Diócesis de Málaga-Soatá', 'diocesis'),
    ('Diócesis de Montería', 'diocesis'),
    ('Diócesis de Montelíbano', 'diocesis'),
    ('Diócesis de Neiva', 'diocesis'),
    ('Diócesis de Ocaña', 'diocesis'),
    ('Diócesis de Palmira', 'diocesis'),
    ('Diócesis de Pereira', 'diocesis'),
    ('Diócesis de Pasto', 'diocesis'),
    ('Diócesis de Quibdó', 'diocesis'),
    ('Diócesis de Riohacha', 'diocesis'),
    ('Diócesis de San Gil', 'diocesis'),
    ('Diócesis de San José del Guaviare', 'diocesis'),
    ('Diócesis de Santa Marta', 'diocesis'),
    ('Diócesis de Santa Rosa de Osos', 'diocesis'),
    ('Diócesis de Sincelejo', 'diocesis'),
    ('Diócesis de Socorro y San Gil', 'diocesis'),
    ('Diócesis de Sonsón-Rionegro', 'diocesis'),
    ('Diócesis de Soacha', 'diocesis'),
    ('Diócesis de Tibú', 'diocesis'),
    ('Diócesis de Tumaco', 'diocesis'),
    ('Diócesis de Valledupar', 'diocesis'),
    ('Diócesis de Vélez', 'diocesis'),
    ('Diócesis de Yopal', 'diocesis'),
    ('Diócesis de Zipaquirá', 'diocesis'),
    ('Diócesis de Cali', 'diocesis'),
    ('Diócesis de Buenaventura', 'diocesis'),
    ('Diócesis de El Banco', 'diocesis'),
    ('Diócesis de Arauca', 'diocesis'),
    ('Diócesis de Sahagún', 'diocesis');

-- Vicariatos Apostólicos (10)
INSERT INTO public.dioceses (name, type) VALUES
    ('Vicariato Apostólico de Guapi', 'vicariato_apostolico'),
    ('Vicariato Apostólico de Inírida', 'vicariato_apostolico'),
    ('Vicariato Apostólico de Leticia', 'vicariato_apostolico'),
    ('Vicariato Apostólico de Mitú', 'vicariato_apostolico'),
    ('Vicariato Apostólico de Puerto Carreño', 'vicariato_apostolico'),
    ('Vicariato Apostólico de Puerto Gaitán', 'vicariato_apostolico'),
    ('Vicariato Apostólico de Puerto Leguízamo-Solano', 'vicariato_apostolico'),
    ('Vicariato Apostólico de San Andrés y Providencia', 'vicariato_apostolico'),
    ('Vicariato Apostólico de Trinidad', 'vicariato_apostolico'),
    ('Vicariato Apostólico de Tierradentro', 'vicariato_apostolico');

-- Ordinariato Militar (1)
INSERT INTO public.dioceses (name, type) VALUES
    ('Ordinariato Militar de Colombia', 'ordinariato_militar');

-- Exarcado Apostólico (1)
INSERT INTO public.dioceses (name, type) VALUES
    ('Exarcado Apostólico para los fieles de rito oriental en Colombia', 'exarcado_apostolico');

-- ==============================================
-- 3. Add diocese_id FK column to parishes
-- ==============================================
ALTER TABLE public.parishes ADD COLUMN diocese_id bigint REFERENCES public.dioceses(id);

-- ==============================================
-- 4. Migrate existing text data to FK
-- ==============================================
UPDATE public.parishes
SET diocese_id = (SELECT id FROM public.dioceses WHERE name = parishes.diocese)
WHERE diocese IS NOT NULL AND diocese != '';

-- ==============================================
-- 5. Drop views that depend on parishes.diocese, then drop the column
-- ==============================================
DROP VIEW IF EXISTS view_communities_by_parish;
DROP VIEW IF EXISTS view_priests_report;

ALTER TABLE public.parishes DROP COLUMN diocese;

-- ==============================================
-- 6. Create index on the new FK
-- ==============================================
CREATE INDEX idx_parishes_diocese_id ON public.parishes(diocese_id);

-- ==============================================
-- 7. RLS for dioceses table
-- ==============================================
ALTER TABLE public.dioceses ENABLE ROW LEVEL SECURITY;

CREATE POLICY "dioceses_select_authenticated" ON public.dioceses
    FOR SELECT
    TO authenticated
    USING (true);

CREATE POLICY "dioceses_insert_contributor_admin" ON public.dioceses
    FOR INSERT
    TO authenticated
    WITH CHECK (public.is_contributor_or_admin());

CREATE POLICY "dioceses_update_contributor_admin" ON public.dioceses
    FOR UPDATE
    TO authenticated
    USING (public.is_contributor_or_admin())
    WITH CHECK (public.is_contributor_or_admin());

CREATE POLICY "dioceses_delete_admin" ON public.dioceses
    FOR DELETE
    TO authenticated
    USING (public.is_admin());

-- ==============================================
-- 8. Recreate views to use JOIN to dioceses
-- ==============================================

-- Recreate view_communities_by_parish
CREATE OR REPLACE VIEW view_communities_by_parish AS
SELECT
    p.id as parish_id,
    p.name as parish_name,
    COALESCE(d.name, 'No especificado') as diocese,
    ci.name as city_name,
    COUNT(c.id) as communities_count,
    COALESCE(SUM(c.actual_brothers), 0) as total_brothers,
    CASE
        WHEN COUNT(c.id) > 0
        THEN ROUND(COALESCE(SUM(c.actual_brothers), 0)::numeric / COUNT(c.id), 2)
        ELSE 0
    END as avg_brothers_per_community,
    STRING_AGG(DISTINCT sw.name, ', ') as step_ways_summary
FROM parishes p
JOIN cities ci ON p.city_id = ci.id
LEFT JOIN dioceses d ON p.diocese_id = d.id
LEFT JOIN communities c ON p.id = c.parish_id
LEFT JOIN step_ways sw ON c.step_way_id = sw.id
GROUP BY p.id, p.name, d.name, ci.name
HAVING COUNT(c.id) > 0;

-- Recreate view_priests_report
CREATE OR REPLACE VIEW view_priests_report AS
SELECT
    pr.id as priest_id,
    pe.person_name as priest_name,
    COALESCE(pe.phone, '-') as phone,
    COALESCE(pe.mobile, '-') as mobile,
    COALESCE(pe.email, '-') as email,
    pr.is_parish_priest,
    COALESCE(p.name, 'Sin parroquia asignada') as parish_name,
    COALESCE(d.name, 'No especificado') as diocese,
    COALESCE(ci.name, 'N/A') as city_name,
    COUNT(c.id) as communities_count
FROM priests pr
JOIN people pe ON pr.person_id = pe.id
LEFT JOIN parishes p ON pr.parish_id = p.id
LEFT JOIN dioceses d ON p.diocese_id = d.id
LEFT JOIN cities ci ON p.city_id = ci.id
LEFT JOIN communities c ON p.id = c.parish_id
GROUP BY pr.id, pe.person_name, pe.phone, pe.mobile, pe.email,
         pr.is_parish_priest, p.name, d.name, ci.name
ORDER BY pe.person_name;

COMMIT;
