-- ==============================================
-- ADD CITY ZONES
-- ==============================================
-- Adds zone support for parishes within cities.
-- Each city can have its own set of zones (e.g., "Zona Norte", "Zona Sur").
-- Parishes can optionally be assigned to a zone within their city.
-- ==============================================

-- 1. Create city_zones table
CREATE TABLE public.city_zones (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name varchar(256) NOT NULL,
  city_id bigint NOT NULL REFERENCES public.cities(id),
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- Unique constraint: zone name must be unique within a city
ALTER TABLE public.city_zones ADD CONSTRAINT city_zones_name_city_unique UNIQUE (name, city_id);

-- Index for city_id lookups
CREATE INDEX city_zones_city_id_idx ON public.city_zones(city_id);

-- Enable RLS
ALTER TABLE public.city_zones ENABLE ROW LEVEL SECURITY;

-- RLS Policies (same pattern as cities)
CREATE POLICY "city_zones_select_authenticated" ON public.city_zones
  FOR SELECT
  TO authenticated
  USING (true);

CREATE POLICY "city_zones_insert_contributor_admin" ON public.city_zones
  FOR INSERT
  TO authenticated
  WITH CHECK (public.is_contributor_or_admin());

CREATE POLICY "city_zones_update_contributor_admin" ON public.city_zones
  FOR UPDATE
  TO authenticated
  USING (public.is_contributor_or_admin())
  WITH CHECK (public.is_contributor_or_admin());

CREATE POLICY "city_zones_delete_admin" ON public.city_zones
  FOR DELETE
  TO authenticated
  USING (public.is_admin());

-- 2. Add zone_id to parishes
ALTER TABLE public.parishes ADD COLUMN zone_id bigint REFERENCES public.city_zones(id);

-- Index for zone_id lookups
CREATE INDEX parishes_zone_id_idx ON public.parishes(zone_id);

