-- ============================================================
-- Audit Log: automatic change tracking for community-related tables
-- ============================================================

-- 1. Create the audit_log table
CREATE TABLE public.audit_log (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id uuid NOT NULL REFERENCES auth.users(id),
  table_name text NOT NULL,
  record_id bigint NOT NULL,
  operation text NOT NULL CHECK (operation IN ('INSERT', 'UPDATE', 'DELETE')),
  community_id bigint REFERENCES communities(id) ON DELETE SET NULL,
  old_values jsonb,
  new_values jsonb,
  changed_columns text[],
  created_at timestamptz NOT NULL DEFAULT now()
);

-- FK to profiles for PostgREST join support
ALTER TABLE public.audit_log
  ADD CONSTRAINT audit_log_user_id_profiles_fkey
  FOREIGN KEY (user_id) REFERENCES public.profiles(id);

-- 2. Indexes
CREATE INDEX idx_audit_log_community_created ON public.audit_log (community_id, created_at DESC);
CREATE INDEX idx_audit_log_user ON public.audit_log (user_id);
CREATE INDEX idx_audit_log_table ON public.audit_log (table_name);
CREATE INDEX idx_audit_log_created ON public.audit_log (created_at DESC);

-- 3. RLS
ALTER TABLE public.audit_log ENABLE ROW LEVEL SECURITY;

-- Admin can see all audit logs; non-admin can only see their own actions
CREATE POLICY "audit_log_select" ON public.audit_log
  FOR SELECT
  USING (public.is_admin() OR user_id = auth.uid());

-- Insert is done by the trigger (SECURITY DEFINER), but we also allow
-- authenticated users so the trigger can write on their behalf
CREATE POLICY "audit_log_insert" ON public.audit_log
  FOR INSERT
  WITH CHECK (true);

-- Logs are immutable: no UPDATE or DELETE allowed
-- (no policies = denied by default with RLS enabled)

-- 4. Generic audit trigger function
CREATE OR REPLACE FUNCTION public.audit_log_trigger()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  _user_id uuid;
  _community_id bigint;
  _record_id bigint;
  _old jsonb;
  _new jsonb;
  _changed text[];
  _key text;
BEGIN
  -- Get the authenticated user; skip if no user (seeds/migrations)
  _user_id := auth.uid();
  IF _user_id IS NULL THEN
    RETURN COALESCE(NEW, OLD);
  END IF;

  -- Determine record_id
  IF TG_OP = 'DELETE' THEN
    _record_id := OLD.id;
  ELSE
    _record_id := NEW.id;
  END IF;

  -- Determine community_id based on table
  IF TG_TABLE_NAME = 'communities' THEN
    IF TG_OP = 'DELETE' THEN
      _community_id := OLD.id;
    ELSE
      _community_id := NEW.id;
    END IF;
  ELSE
    -- All other tracked tables have a community_id column
    IF TG_OP = 'DELETE' THEN
      _community_id := OLD.community_id;
    ELSE
      _community_id := NEW.community_id;
    END IF;
  END IF;

  -- Build old/new JSONB and changed_columns
  IF TG_OP = 'INSERT' THEN
    _old := NULL;
    _new := to_jsonb(NEW);
    _changed := NULL;

  ELSIF TG_OP = 'UPDATE' THEN
    _old := to_jsonb(OLD);
    _new := to_jsonb(NEW);

    -- Calculate which columns actually changed
    _changed := ARRAY(
      SELECT key
      FROM jsonb_each(_new) AS n(key, value)
      WHERE n.key NOT IN ('updated_at')
        AND (_old ->> n.key) IS DISTINCT FROM (_new ->> n.key)
    );

    -- Skip if nothing actually changed
    IF array_length(_changed, 1) IS NULL THEN
      RETURN NEW;
    END IF;

  ELSIF TG_OP = 'DELETE' THEN
    _old := to_jsonb(OLD);
    _new := NULL;
    _changed := NULL;
  END IF;

  -- Insert the audit record
  INSERT INTO public.audit_log (user_id, table_name, record_id, operation, community_id, old_values, new_values, changed_columns)
  VALUES (_user_id, TG_TABLE_NAME, _record_id, TG_OP, _community_id, _old, _new, _changed);

  RETURN COALESCE(NEW, OLD);
END;
$$;

-- 5. Attach triggers to tracked tables
CREATE TRIGGER audit_communities
  AFTER INSERT OR UPDATE OR DELETE ON public.communities
  FOR EACH ROW EXECUTE FUNCTION public.audit_log_trigger();

CREATE TRIGGER audit_teams
  AFTER INSERT OR UPDATE OR DELETE ON public.teams
  FOR EACH ROW EXECUTE FUNCTION public.audit_log_trigger();

CREATE TRIGGER audit_brothers
  AFTER INSERT OR UPDATE OR DELETE ON public.brothers
  FOR EACH ROW EXECUTE FUNCTION public.audit_log_trigger();

CREATE TRIGGER audit_belongs
  AFTER INSERT OR UPDATE OR DELETE ON public.belongs
  FOR EACH ROW EXECUTE FUNCTION public.audit_log_trigger();

CREATE TRIGGER audit_community_step_log
  AFTER INSERT OR UPDATE OR DELETE ON public.community_step_log
  FOR EACH ROW EXECUTE FUNCTION public.audit_log_trigger();
