-- Parish Catechesis history table
create table parish_catechesis (
  id bigint primary key generated by default as identity,
  parish_id bigint not null references parishes(id) on delete cascade,
  planned_start_date date,
  actual_start_date date,
  birth_retreat_date date,
  attendance_count integer,
  catechist_team text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.parish_catechesis enable row level security;

-- RLS policies (same pattern as community_step_log)
create policy "Enable read access for all users" on parish_catechesis
  for select using (true);

create policy "Enable insert for authenticated users only" on parish_catechesis
  for insert with check (auth.role() = 'authenticated');

create policy "Enable update for authenticated users only" on parish_catechesis
  for update using (auth.role() = 'authenticated');

create policy "Enable delete for authenticated users only" on parish_catechesis
  for delete using (auth.role() = 'authenticated');

-- Trigger for updated_at
create or replace function public.handle_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create trigger set_parish_catechesis_updated_at
  before update on parish_catechesis
  for each row
  execute function public.handle_updated_at();
